site_name: Cardano read ledger library
site_url: https://paolino.github.io/cardano-read-ledger/
repo_url: https://github.com/paolino/cardano-read-ledger

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - navigation.path

plugins:
  - search
  - asciinema-player

markdown_extensions:
  - callouts